#!/usr/bin/env php
<?php
// Script should not be called from the Web
if (php_sapi_name() != 'cli') {
    die('Nope');
}

date_default_timezone_set('Europe/Paris');

require_once __DIR__ . '/inc/init.php';

/* init l10n class to create the globals needed */
$initl10n = new l10n_moz();

/* user provided variables */
$filename = isset($argv[1]) ? secureText($argv[1])  : 'main.lang'; // which file are we comparing? Set a default
$website  = isset($argv[2]) ? secureText($argv[2])  : '0'; // which website are we looking at? Default to www.mozilla.org
$locale   = isset($argv[3]) ? secureText($argv[3])  : 'all';  // which locale are we analysing? No default

if ($filename == 'all') {
    $files = array_keys($langfiles_subsets[$sites[$website][0]]);
} else {
    $files = array($filename);
}

/* loop generating the files */
foreach ($files as $filename) {

    // load the English source for the file

    $reflang  = $sites[$website][5];
    $source   = $sites[$website][1] . $sites[$website][2] . $reflang . '/' . $filename;
    logger("Reference English file: $source");

    if (
        $locale != 'all'
        && $locale != 'locamotion'
        && in_array($locale, $langfiles_subsets[$sites[$website][0]][$filename])
        )
    {
        $locales = array($locale);
    } elseif (
        $locale != 'all'
        && $locale != 'locamotion'
        && !in_array($locale, $langfiles_subsets[$sites[$website][0]][$filename])
        )
    {
        // locale is not supported for the lang file, skip
        continue;
    } elseif ($locale == 'locamotion') {
        $locales = array_intersect($locamotion_locales, $langfiles_subsets[$sites[$website][0]][$filename]);
    } else {
        $locales = $langfiles_subsets[$sites[$website][0]][$filename];
    }

    getEnglishSource($reflang, $website, $filename, 1);

    // When we analyse multiple files we don't want to stop for lack of source
    if (count($files) == 1) {
        if ($GLOBALS['__english_moz'] == null) {
            logger("$source does not exist", 'quit');
        }
    }

    if (isset($langfiles_subsets[$sites[$website][0]][$filename])) {
        $result = '';
        foreach ($locales as $lang) {

            $source = $sites[$website][1] . $sites[$website][2] . $lang . '/' . $filename;

            // delete translations from memory before processing locale
            if (isset($GLOBALS['__l10n_moz'])) {
                unset($GLOBALS['__l10n_moz']);
            }

            /* here we load preexisting lang files */
            l10n_moz::load($source);

            /* is the lang file using Windows or Unix EOL? */
            if (file_exists($source)) {
                $eol = file($source);
                $eol = isWindowsEOL($eol[0]) ? "\r\n" : "\n";
            } else {
                $eol = "\n";
            }

            $activeStatus = (boolean) $GLOBALS['__l10n_moz']['activated'];

            /* import data from locamotion */
            if ($locale == 'locamotion') {
                $import = scrapLocamotion($lang, $filename, $source);
                if (!$import) {
                    continue;
                }
            }
            /* incorporate strings from other lang files */
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/survey1.lang');
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/survey2.lang');
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/survey3.lang');
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/survey4.lang');
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/survey5.lang');
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/snippets.lang');
            // l10n_moz::load($sites[$website][1] . $sites[$website][2] . $lang . '/mozorg/about.lang');

            $GLOBALS['__l10n_moz']['activated'] = (boolean) $activeStatus;
            $GLOBALS['__l10n_moz']['locale_code'] = $lang;

            $exceptions = array(
                // new string => older equivalent string
                'Spain with <a href="%s">Movistar</a>'      => strip_tags('Spain with <a href="%s">Movistar</a>'),
                'Poland with <a href="%s">T-Mobile</a>'     => strip_tags('Poland with <a href="%s">T-Mobile</a>'),
                'Venezuela with <a href="%s">Movistar</a>'  => strip_tags('Venezuela with <a href="%s">Movistar</a>'),
                'Colombia with <a href="%s">Movistar</a>'   => strip_tags('Colombia with <a href="%s">Movistar</a>'),
                'Hungary with both <a href="%s">Telenor</a> and <a href="%s">T-Mobile</a>'  => 'Hungary with both <a href="%s">Telenor</a> and <a href="%s">Telekom</a>',
                'Peru with <a href="%s">Movistar</a>'       => strip_tags('Peru with <a href="%s">Movistar</a>'),
                'Serbia with <a href="%s">Telenor</a>'      => strip_tags('Serbia with <a href="%s">Telenor</a>'),
                'Montenegro with <a href="%s">Telenor</a>'  => strip_tags('Montenegro with <a href="%s">Telenor</a>'),
                'Greece with <a href="%s">Cosmote</a>'      => strip_tags('Greece with <a href="%s">Cosmote</a>'),
                'Germany with <a href="%s">Congstar</a>'    => strip_tags('Germany with <a href="%s">Congstar</a>'),
                'Brazil with <a href="%s">Vivo</a>'         => strip_tags('Brazil with <a href="%s">Vivo</a>'),
                'Mexico with <a href="%s">Movistar</a>'     => strip_tags('Mexico with <a href="%s">Movistar</a>'),
                'Italy with <a href="%s">TIM</a>'           => strip_tags('Italy with <a href="%s">TIM</a>'),
                'Uruguay with <a href="%s">Movistar</a>'    => strip_tags('Uruguay with <a href="%s">Movistar</a>'),
            );

            $content = buildFile($eol, $exceptions);
            $path    = $source;
            //~ print_r($content);die; //debug

            fileForceContents($path, $content);

            $result .= $lang  . ': ' . $filename . $eol;

        }
        // delete source English strings from memory before loading next file
        if (isset($GLOBALS['__english_moz'])) {
            unset($GLOBALS['__english_moz']);
        }

        logger($result);
    }
}
