#!/usr/bin/env php
<?php

date_default_timezone_set('Europe/Paris');
include __DIR__ .'/libs/poparser.php';

if (php_sapi_name() != 'cli') {
    die('Nope');
}

require_once __DIR__ . '/inc/init.php';

/* init l10n class to create the globals needed */
$initl10n = new l10n_moz();

/* user provided variables */
$filename   = (isset($argv[1])) ? secureText($argv[1]) : 'main.lang'; // which file are we comparing? Set a default
$website    = (isset($argv[2])) ? secureText($argv[2])  : '0'; // which website are we looking at? Default to www.mozilla.org
$locale     = (isset($argv[3])) ? secureText($argv[3])  : 'all';  // which locale are we analysing? No default

/* temp variables */
$reflang  = $sites[$website][5];
$source   = $sites[$website][1] . $sites[$website][2] . $reflang . '/' . $filename;

error_log("Reference English file: $source \n");

getEnglishSource($reflang, $website, $filename, 1);

if ($GLOBALS['__english_moz'] == null) {
    die("$source does not exist");
}

if ($filename == 'all') {
    $files = $langfiles_subsets[$sites[$website][0]];
} else {
    $files = array($filename);
}

if ($locale != 'all' && in_array($locale, $langfiles_subsets[$sites[$website][0]][$filename])) {
    $locales = array($locale);
} elseif ($locale == 'locamotion') {
    $locales = array_intersect($locamotion_locales, $langfiles_subsets[$sites[$website][0]][$filename]);
} else {
    $locales = $langfiles_subsets[$sites[$website][0]][$filename];
}

/* loop generating the files */
foreach ($files as $filename) {
    if (isset($langfiles_subsets[$sites[$website][0]][$filename])) {
        $result = '';
        foreach ($locales as $_lang) {

            $source = $sites[$website][1] . $sites[$website][2] . $_lang . '/' . $filename;

            /* here we load preexisting lang files */
            l10n_moz::load($source);

            /* is the lang file using Windows or Unix EOL? */
            if (file_exists($source)) {
                $eol = file($source);
                $eol = isWindowsEOL($eol[0]) ? "\r\n" : "\n";
            } else {
                $eol = "\n";
            }

            $activeStatus = (boolean) $GLOBALS['__l10n_moz']['activated'];

            /* import data from locamotion */
            if ($locale == 'locamotion') {
                scrapLocamotion($_lang, $filename, $source);
            }
            /* incorporate strings from other lang files */
            //~ l10n_moz::load($sites[$website][1] . $sites[$website][2] . $_lang . '/survey1.lang');
            //~ l10n_moz::load($sites[$website][1] . $sites[$website][2] . $_lang . '/survey2.lang');
            //~ l10n_moz::load($sites[$website][1] . $sites[$website][2] . $_lang . '/survey3.lang');
            //~ l10n_moz::load($sites[$website][1] . $sites[$website][2] . $_lang . '/snippets.lang');
            //~ l10n_moz::load($sites[$website][1] . $sites[$website][2] . $_lang . '/mozorg/about.lang');

            $GLOBALS['__l10n_moz']['activated'] = (boolean) $activeStatus;

            $exceptions = array(
                // new string => older equivalent string
                'Different by design'           => 'Different by Design',
                'Proudly<br />non-profit'       => 'Proudly <span>non-profit</span>',
                'Innovating<br />for you'       => 'Innovating <span>for you</span>',
                'Fast, flexible,<br />secure'   => 'Fast, flexible, <span>secure</span>',
            );

            $exceptions = array(
                //~ 'Mozilla and partners prepare to launch first Firefox OS smartphones' => 'Mozilla and partners prepare to launch first Firefox OS smartsphones'
            );

            $content = buildFile($eol, $exceptions);
            $path    = $source;
            //~ print_r($content);die; //debug

            fileForceContents($path, $content);

            $result .= $_lang  . ': ' . $filename . $eol;

            if (isset($GLOBALS['__l10n_moz'])) {
                unset($GLOBALS['__l10n_moz']);
            }
        }
        error_log($result);
    }
}
