#!/usr/bin/env php
<?php

date_default_timezone_set('Europe/Paris');

if (php_sapi_name() != 'cli') {
    die('This command can only be used in CLI mode.');
}

if (isset($argv[1])) {
    if ($argv[1] == '-h' || $argv[1] == '--help' ) {
        print "mark_active - Add the ## active ## tag to lang files completed on www.mozilla.org\n";
        print "Usage: mark_active [file]\n";
        print "Example: mark_active firefox/new.lang\n";
        die();
    }
}

if (count($argv) < 2) {
    die("This command needs more options, please check mark_active --help.\n");
}

/* Rename user provided variables */
$lang_file = $argv[1];

/* Script variables */
$local_repo = __DIR__ . '/locales/';
$langchecker = 'http://l10n.mozilla-community.org/~pascalc/langchecker/?locale=all&website=0&json&file=';
$file_status = json_decode(file_get_contents($langchecker . $lang_file), true)[$lang_file];

/* Commodity functions to prepend */
function activate($file) {
    $exploded_file = file($file);
    if (trim($exploded_file[0]) == '## active ##') {
        return 0;
    }

    $status = file_put_contents($file, "## active ##\n" . implode($exploded_file));
    return $status === false ? 1 : 2;
}

$activate = function(array $file_status) {
    $list = [];

    foreach ($file_status as $locale => $details) {
        if ($details['activated']) {
            continue;
        }

        if ($details['Identical'] == 0 && $details['Missing'] == 0) {
            $list[] = $locale;
        }
    }

    return $list;
};

/* Activate locales */
foreach ($activate($file_status) as $locale) {
    $activation_status = activate($local_repo . $locale . '/' . $lang_file);
    switch($activation_status) {
        case 0:
            print "{$locale}/{$lang_file} already has the active tag!\n";
            break;
        case 1:
            print "ERROR: {$locale}/{$lang_file} could not be marked as active!\n";
            break;
        case 2:
            print "{$locale}/{$lang_file} now has the active tag\n";
            break;
    }
}
