#!/usr/bin/env php
<?php
namespace Langchecker;

$command_help = "mark_active - Add the ## active ## tag to complete lang files on www.mozilla.org\n" .
                "Usage: mark_active [filename]\n\n" .
                "Example: mark_active firefox/new.lang\n";
$min_parameters = 1;
$missing_parameter = "This command needs more parameters, please check mark_active --help.\n";

require_once __DIR__ . '/../inc/cli_init.php';

// This script is relevant only for mozilla.org
$current_website = $sites[0];
$current_filename = Utils::getCliParam(1, $argv, '');

if (in_array($current_filename, $no_active_tag)) {
    die("This file is not supposed to be activated.\n");
}

if (Project::isObsoleteFile($current_website, $current_filename, 'all')) {
    die("This file is obsolete and is not supposed to be activated.\n");
}

// Read reference data once
$reference_locale = Project::getReferenceLocale($current_website);
$reference_data = LangManager::loadSource($current_website, $reference_locale, $current_filename);

$supported_locales = Project::getSupportedLocales($current_website, $current_filename);
$results = [
    'activated'  => [],
    'active'     => [],
    'errors'     => [],
    'incomplete' => [],
];

foreach ($supported_locales as $current_locale) {
    // Ignore locale if it's the reference language
    if ($current_locale == $reference_locale) {
        continue;
    }
    // If the .lang file does not exist, just skip the locale for this file
    if (! file_exists(Project::getLocalFilePath($current_website, $current_locale, $current_filename))) {
        continue;
    }
    $locale_filename = Project::getLocalFilePath($current_website, $current_locale, $current_filename);
    $locale_analysis = LangManager::analyzeLangFile($current_website, $current_locale, $current_filename, $reference_data);

    $todo = count($locale_analysis['Identical']) +
            count($locale_analysis['Missing']) +
            LangManager::countErrors($locale_analysis['errors']);
    if ($todo == 0) {
        // If file is ready and not activated, add the ## active ## tag
        if (! $locale_analysis['activated']) {
            $file_content = file($locale_filename);
            $eol = Utils::checkEOL($file_content[0]);
            $write_status = file_put_contents($locale_filename, "## active ##{$eol}" . implode($file_content));
            if ($write_status === false) {
                array_push($results['errors'], $current_locale);
            } else {
                array_push($results['activated'], $current_locale);
            }
        } else {
            array_push($results['active'], $current_locale);
        }
    } else {
        array_push($results['incomplete'], $current_locale);
    }
}

// Make sure there's something to display in console
$results = array_map(
    function ($element) {
        if (count($element) == 0) {
            $element = ['-'];
        }

        return $element;
    },
    $results
);

print "\nResults for {$current_filename}:";
print "\nActivated: " . implode(', ', $results['activated']);
print "\nAlready activated: " . implode(', ', $results['active']);
print "\nIncomplete: " . implode(', ', $results['incomplete']);
print "\nWrite errors: " . implode(', ', $results['errors']) . "\n";
