#!/usr/bin/env php
<?php
namespace Langchecker;

$command_help = "mark_active - Add the ## active ## tag to complete lang files on www.mozilla.org\n" .
                "Usage: mark_active [filename]\n\n" .
                "Example: mark_active firefox/new.lang\n";
$min_parameters = 1;
$missing_parameter = "This command needs more parameters, please check mark_active --help.\n";

require_once __DIR__ . '/../inc/cli_init.php';

// Only mozilla.org
$current_website = $sites[0];
$current_filename = Utils::getCliParam(1, $argv, '');

if (in_array($current_filename, $no_active_tag)) {
    die("This file is not supposed to be activated.\n");
}

if (Project::isObsoleteFile($current_website, $current_filename, 'all')) {
    die("This file is obsolete and is not supposed to be activated.\n");
}

// Read reference data once
$reference_locale = Project::getReferenceLocale($current_website);
$reference_data = LangManager::loadSource($current_website, $reference_locale, $current_filename);

$supported_locales = Project::getSupportedLocales($current_website, $current_filename, $langfiles_subsets);
$results = [
    'activated'  => [],
    'active'     => [],
    'errors'     => [],
    'incomplete' => [],
];

foreach ($supported_locales as $current_locale) {
    if ($current_locale == $reference_locale) {
        // Ignore reference language
        continue;
    }
    if (! file_exists(Project::getLocalFilePath($current_website, $current_locale, $current_filename))) {
        // If the .lang file does not exist, just skip the locale for this file
        continue;
    }
    $locale_filename = Project::getLocalFilePath($current_website, $current_locale, $current_filename);
    $locale_analysis = LangManager::analyzeLangFile($current_website, $current_locale, $current_filename, $reference_data);

    $todo = count($locale_analysis['Identical']) +
            count($locale_analysis['Missing']) +
            LangManager::countErrors($locale_analysis['errors']);
    if ($todo == 0) {
        if (! $locale_analysis['activated']) {
            // File is ready, add ## active ## tag
            $file_content = file($locale_filename);
            $eol = Utils::checkEOL($file_content[0]);
            $write_status = file_put_contents($locale_filename, "## active ##{$eol}" . implode($file_content));
            if ($write_status === false) {
                array_push($results['errors'], $current_locale);
            } else {
                array_push($results['activated'], $current_locale);
            }
        } else {
            array_push($results['active'], $current_locale);
        }
    } else {
        array_push($results['incomplete'], $current_locale);
    }
}

// Make sure there's something to display
$results = array_map(
    function ($element) {
        if (count($element) == 0) {
            $element = ['-'];
        }

        return $element;
    },
    $results
);

print "\nResults for {$current_filename}:";
print "\n\nActivated: " . implode(', ', $results['activated']);
print "\n\nAlready activated: " . implode(', ', $results['active']);
print "\n\nIncomplete: " . implode(', ', $results['incomplete']);
print "\n\nWrite errors: " . implode(', ', $results['errors']) . "\n";
