#!/usr/bin/env php
<?php

require_once __DIR__ . '/../inc/init.php';

foreach ($repositories as $repository_id => $repository) {
    system(
        "{$app_folder}scripts/update_repository.sh {$repository['vcs']} {$repository_id} {$repository['repository']} {$repository['local_path']}"
    );
}
