name: Run Tests
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0', '7.2', '7.4']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Install Node packages
        run: npm install -g eslint

      - name: Run JS linter (eslint)
        run: eslint web/assets/js

      - name: Run PHP linter (php-cs-fixer)
        run: vendor/bin/php-cs-fixer --diff --dry-run -v fix

      - name: Run tests
        run: |
          cp app/config/settings.inc.php.ini app/config/settings.inc.php
          vendor/atoum/atoum/bin/atoum -d tests/units/ --use-light-report
          php tests/functional/api.php
          php tests/integrity/source_integrity.php
